version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: laravel_image
    container_name: laravel_container
    restart: unless-stopped
   
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    environment:
      - APP_ENV=local
    networks:
      - app-network

  vue:
    build:
      context: ../../vuejs
      dockerfile: Dockerfile
    image: vuejs_image
    container_name: vue_container
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mysql:8.0.39-debian
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yowl
      MYSQL_PASSWORD: florette1234
      MYSQL_USER: florette
    networks:
      - app-network
    ports:
      - "3001:3001"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

